import type { NextPage } from 'next'
import Head from 'next/head'
import Calendar from '../../components/Calendar/Calendar'
import Header from '../../components/common/Header/Header'
import styles from '../../styles/Home.module.css'

const Media: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>Kawaii islands | Calendar</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <Header />
            <main className={styles.main}>
                <Calendar />
            </main>
        </div>
    )
}

export default Media;
