import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../../components/common/Header/Header'
import MediaKit from '../../components/MediaKit/MediaKit'
import styles from '../../styles/Home.module.css'

const Media: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={styles.main}>
        <MediaKit />
      </main>
    </div>
  )
}

export default Media;
